
using System.Collections.Generic;

namespace DeepState.Data.Constants
{
	public static class HungerGameConstants
	{
		public const double CostOfAdmission = 0.00001;
		public static string HungerGameTributesEmbedTitle { get; set; } = "⛈️ **T H U N D E R D O M E TRIBUTES** ⛈️";
		public static string RandomTributeWeaponKill { get; set; } = "TributeWeaponKill";
		public static string RandomTributeWeaponKillFormat { get; set; } = "{0} killed {1} with {2}";

		public const string TributeRoleName = "Tribute";
		public const string ChampionRoleName = "⛈️CHAMPION⛈️";

		public static List<string> Weapons = new List<string>
		{
			"a Halibut.",
			"an AK-47.",
			"a Deagle.",
			"Gwalms' Body?!",
			"a Katana.",
			"a Sword (Great).",
			"a Sword (Short).",
			"a Sword (Bastard).",
			"a Sword (Fish).",
			"a Great Axe.",
			"a Hand Axe.",
			"a Bong.",
			"an Icepick.",
			"a Type 100 SMG.",
			"a Skorpion (the gun).",
			"a Scorpion (the arachnid).",
			"a StG-44.",
			"an XM8.",
			"a FG-42.",
			"an H&K G11.",
			"a Japanese Type 5.",
			"a PTRS-41.",
			"a PP-2000.",
			"a G-42.",
			"a Golden Gun.",
			"a Spartan Lazer.",
			"an Empty Bottle of Everclear.",
			"a G-43.",
			"a WA-2000.",
			"a Super Cool!!!! Mech.",
			"a Covenant Energy Sword.",
			"a Hidden Blade.",
			"a Gravity Gun.",
			"the Master Sword.",
			"a Keyblade.",
			"a BFG-9001.",
			"the Mega-Buster.",
			"the Blades of Chaos.",
			"a Frying Pan.",
			"a Orbital Bombardment.",
			"a Rod from God missile.",
			"the Moon.",
			"Hydroxychloriquine.",
			"a Syringe filled with Bleach labeled 'Virus-Killing Science Juice'.",
			"Jeb's `PLEASE CLAP` sign.",
			"a (sabotauged) Faulty O-Ring.",
			"a Tesla, in autopilot mode.",
			"an ICMB.",
			"a battleaxe.",
			"a dagger.",
			"a sickle.",
			"a rapier.",
			"a rake.",
			"a kitchen knife.",
			"a scimitar.",
			"a swiss army knife.",
			"a chainsaw.",
			"a cleaver.",
			"a MOTHERFUCKING LIGHTNING BOLT.",
			"a Time Machine and a very small pillow.",
			"a cashed-in favor from Dagon.",
			"a cashed-in favor from D9.",
			"a cashed-in favor from Cthulhu.",
			"a cashed-in favor from President Biden.",
			"a Million God-Damn Mosquitos.",
			"their Bare Hands.",
			"their Bear Hands.",
			"a spoon.",
			"both barrels of a Sawed-Off Shotgun.",
			"a Mateba Unica 6.",
			"a Hamster. Do Not Ask.",
			"the Sword that Gwindor gave to Túrin, who knew that it was heavy and strong and had great power; but its blade was black and dull and its edges blunt. Then Gwindor said: 'This is a strange blade, and unlike any that I have seen in Middle-earth.'",
			"a Big-Iron (worn on their hips).",
			"a Wooden Steak.",
			"a Wooden Stake.",
			"a Meaty Steak.",
			"their MIND !!!!!",
			"the Force.",
			"an Easily Exploitable Bug. Fucking Hackers.",
			"a Fat-Man portable nuke launcher.",
			"a Typewriter (Bludgeoning)",
			"a Typewriter (Character Assassination. Then Bludgeoning.)",
			"the Thu'um. FUS RO DEAD!",
			"a Death Note. Cause of Death? Shitting out their organs.",
			"a Death Note. Cause of Death? Spontaneous Combustion.",
			"a Death Note. Cause of Death? Spontaneous DECAPATION!!!!",
			"a Death Note. Cause of Death? Choking on their own tongue.",
			"ONE PUNCH.",
			"a MIGHTY Kamehameha.",
			"a Clank of Tanks.",
			"a Ukelele.",
			"the sickest dance moves you've ever seen!",
		};
	}
}
