// <auto-generated />
using System;
using DeepState.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeepState.Data.Migrations.ModTeamRequest
{
    [DbContext(typeof(ModTeamRequestContext))]
    partial class ModTeamRequestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeepState.Data.Models.ModTeamRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClosingMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 26, 9, 9, 33, 147, DateTimeKind.Local).AddTicks(3246));

                    b.Property<decimal>("DiscordGuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestingUserDiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("modifyingModDiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("RequestId");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
