// <auto-generated />
using DeepState.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeepState.Data.Migrations.RPG
{
    [DbContext(typeof(RPGContext))]
    [Migration("20220212064005_FixItemMigration")]
    partial class FixItemMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeepState.Data.Models.RPGModels.Character", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fortitude")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Hitpoints")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaximumHitpoints")
                        .HasColumnType("int");

                    b.Property<int>("Mobility")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayersMurdered")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<bool>("PvPFlagged")
                        .HasColumnType("bit");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("DiscordUserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DeepState.Data.Models.RPGModels.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("CharacterDiscordUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("item_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.HasIndex("CharacterDiscordUserId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("item_type").HasValue("Item");
                });

            modelBuilder.Entity("DeepState.Data.Models.RPGModels.RPGConfiguration", b =>
                {
                    b.Property<decimal>("DiscordGuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<decimal>("ObituaryChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("RPGConfigs");
                });

            modelBuilder.Entity("DeepState.Data.Models.RPGModels.HealingItem", b =>
                {
                    b.HasBaseType("DeepState.Data.Models.RPGModels.Item");

                    b.Property<string>("ConsumeMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("health_items");
                });

            modelBuilder.Entity("DeepState.Data.Models.RPGModels.Item", b =>
                {
                    b.HasOne("DeepState.Data.Models.RPGModels.Character", null)
                        .WithMany("Items")
                        .HasForeignKey("CharacterDiscordUserId");
                });

            modelBuilder.Entity("DeepState.Data.Models.RPGModels.Character", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
