name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore TheDeepState.sln
    - name: Build
      run: dotnet build --no-restore TheDeepState.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal TheDeepState.sln
    - name: failing step
      continue-on-error: true
      run: dotnet restore
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        tags: otherwisejunk/thedeepstate


